# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0

# https://rhysd.github.io/actionlint/

name: Testing
on: [push]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v4
      with: { path: "ccache", key: "${{ github.job }}-${{hashFiles ('misc/*')}}" }
    - name: Test Linux Build
      run: misc/debianbuild.sh
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-logs
        path: test-logs.tar.xz
    - name: Ping IRC
      if: always()
      run: |
        S="${{ job.status }}" && URL="${{ github.event.head_commit.url }}"
        N="$(git log -1 --format="%cL")" && B="$(git branch --show-current)"
        MSG=$(git log -1 --format="%s")
        .github/workflows/ircbot.py -q -j "#Anklang" -n AnklangGH -U "$N" -D "$B" -S "$S" "$MSG" "$URL"
  linux-arch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v4
      with: { path: "ccache", key: "${{ github.job }}-${{hashFiles ('misc/*')}}" }
    - name: Test Arch Linux Build
      run: misc/archbuild.sh
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-logs-arch
        path: test-logs.tar.xz
  linux-sanitizers:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v4
      with: { path: "ccache", key: "${{ github.job }}-${{hashFiles ('misc/*')}}" }
    - name: Test Linux Build with Sanitizers
      run: misc/debianbuild.sh --enable-asan --enable-ubsan --enable-debug-cxx
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-logs-sanitizers
        path: test-logs.tar.xz
  linux-arch-sanitizers:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v4
      with: { path: "ccache", key: "${{ github.job }}-${{hashFiles ('misc/*')}}" }
    - name: Test Arch Linux Build with Sanitizers
      run: misc/archbuild.sh --enable-asan --enable-ubsan --enable-debug-cxx
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-logs-arch-sanitizers
        path: test-logs.tar.xz
  linux-static:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v4
      with: { path: "ccache", key: "${{ github.job }}-${{hashFiles ('misc/*', 'static/*')}}" }
    - name: Test Build
      run: misc/staticbuild.sh
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test macOS Build
      shell: bash
      run: misc/macbuild.sh
  windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test Windows Build
      run: misc/winbuild.sh
